version: "3.8"

services:
  backend:
    build:
      context: ./backend
      dockerfile: dockerfile
    container_name: backend
    environment:
      - OLLAMA_HOST=http://ollama:11434
      - HOST=0.0.0.0
      - ALLOWED_ORIGINS=${ALLOWED_ORIGINS:-*}
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      - ollama

  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    environment:
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
      - OLLAMA_API_KEY=${OLLAMA_API_KEY}
    ports:
      - "11434:11434"
    volumes:
      - ${OLLAMA_DATA}:/root/.ollama
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: ["gpu"]

  frontend:
    build:
      context: ./frontend
      dockerfile: dockerfile
      args:
        - NEXT_PUBLIC_ADMIN_BACKEND_HOST=${NEXT_PUBLIC_ADMIN_BACKEND_HOST:-http://localhost:8000}
    container_name: frontend
    env_file:
      - .env
    command: "npm run dev"
    restart: always
    volumes:
      - ./frontend/src:/app/src
    ports:
      - "3000:3000"
    environment:
      NEXT_PUBLIC_ADMIN_BACKEND_HOST: ${NEXT_PUBLIC_ADMIN_BACKEND_HOST:-http://localhost:8000}

  mcp-google-services:
    build:
      context: ./mcp/servers/google-services
      dockerfile: Dockerfile
    container_name: mcp-google-services
    volumes:
      - ./mcp/servers/config/token.json:/app/token.json
    ports:
      - "3002:3002"
    environment:
      - PORT=3002
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - GOOGLE_REDIRECT_URI=${GOOGLE_REDIRECT_URI}
    env_file:
      - .env
    depends_on:
      - backend

  mcp-filesystem:
    build:
      context: ./mcp/servers/mcp-filesystem
      dockerfile: Dockerfile
    container_name: mcp-filesystem
    volumes:
      - ${FILE_PATH}:/data
    ports:
      - "3003:3003"
    environment:
      - PORT=3003
      - FILE_PATH=/data
    env_file:
      - .env
    depends_on:
      - backend
