version: "3.8"

services:
  backend:
    build:
      context: ./backend
      dockerfile: dockerfile
    container_name: backend
    environment:
      - OLLAMA_HOST=http://ollama:11434
      - HOST=0.0.0.0
      - ALLOWED_ORIGINS=${ALLOWED_ORIGINS:-*}
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      - ollama

  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    environment:
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
      - OLLAMA_API_KEY=${OLLAMA_API_KEY}
    ports:
      - "11434:11434"
    volumes:
      - ${OLLAMA_DATA}:/root/.ollama
    # nvidia gpu 가속
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: ["gpu"]

  frontend:
    build:
      context: ./frontend
      dockerfile: dockerfile
      args:
        - NEXT_PUBLIC_ADMIN_BACKEND_HOST=${NEXT_PUBLIC_ADMIN_BACKEND_HOST:-http://localhost:8000}
    container_name: frontend
    env_file:
      - .env
    command: "npm run dev"
    restart: always
    volumes:
      - ./frontend/src:/app/src
    ports:
      - "3000:3000"
    environment:
      NEXT_PUBLIC_ADMIN_BACKEND_HOST: ${NEXT_PUBLIC_ADMIN_BACKEND_HOST:-http://localhost:8000}
